trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApp
  displayName: Build Apps
  dependsOn: []
  jobs:
  - job: BuildFrontendApp
    displayName: Build Frontend App
    steps:
    - script: echo building frontend app
      displayName: build frontend app
    - script: echo running unit tests for frontend app
      displayName: unit tests frontend

- stage: DeployDev
  displayName: Deploy to DEV environment
  dependsOn: BuildApp
  jobs:
  - job: DeployFrontendDev
    displayName: Deploy frontend to DEV
    steps:
    - script: echo deploying frontend app to DEV
      displayName: deploy frontend app to DEV

- stage: DeployProd
  displayName: Deploy to PROD environment
  dependsOn: DeployDev
  pool:
    vmImage: 'macOS-10.14'
  jobs:
  - job: DeployFrontendProd
    displayName: Deploy frontend to PROD
    steps:
    - script: echo deploying frontend app to PROD
      displayName: deploy frontend app to PROD
